name: WakaTime Readme

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: ouuan/waka-readme@30days
        with:
          API_BASE_URL: ${{ secrets.WAKAPI_BASE_URL }}
          COMMIT_MESSAGE: Update Wakapi stats
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          BLOCKS: "⬜🟨🟩"